# See the Conductor setup guide at https://packagist.com/docs/conductor/getting-started

on:
  repository_dispatch:
    types:
      - dependency_update

name: Private Packagist Conductor

permissions:
  contents: write

jobs:
  conductor:
    name: Private Packagist Conductor
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # 2.35.3
        with:
          coverage: "none"
          extensions: "intl, zip, apcu"
          php-version: "8.4"

      # See the Conductor GitHub Action at https://github.com/packagist/conductor-github-action
      - name: "Running Conductor"
        uses: packagist/conductor-github-action@b8b726f0038577ba505899dce408b8102d1d75f5 # 1.4.0
