name: "PHP Lint"

on:
  - push
  - pull_request

jobs:
  tests:
    name: "Lint"

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # 2.35.3
        with:
          coverage: "none"
          extensions: "intl"
          php-version: "8.4"

      - name: "Lint PHP files"
        run: "find src/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l -f"
